[program:mysql-backup]
command=/usr/local/bin/mysql-backup.sh
directory=/var/www/html
user=www-data
autostart=true
autorestart=true
startretries=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
stopsignal=TERM
stopwaitsecs=10
