[supervisord]
nodaemon=true
user=root
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[program:php-fpm]
command=php-fpm -F
directory=/var/www/html
user=root
autostart=true
autorestart=true
startretries=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
stopsignal=QUIT
stopwaitsecs=10

[program:nginx]
command=nginx -g "daemon off;"
directory=/var/www/html
user=root
autostart=true
autorestart=true
startretries=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
stopsignal=QUIT
stopwaitsecs=10

[program:horizon]
command=php artisan horizon
directory=/var/www/html
user=www-data
autostart=true
autorestart=true
startretries=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
stopsignal=TERM
stopwaitsecs=10

[program:scheduler]
command=php artisan schedule:work
directory=/var/www/html
user=www-data
autostart=true
autorestart=true
startretries=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
stopsignal=TERM
stopwaitsecs=10

[include]
files = /etc/supervisor/conf.d/*.conf
